# Graph Algorithm

### 자료구조 역시 시간복잡도에 영향


In [ ]:
V = {0:'냄비', 1:'라면봉지', 2:'점화', 3:'라면넣기', 4:'수프넣기', 5:'계란풀기'}
E = {0:[2], 1:[3,4], 2:[3,4,5], 3:[5], 4:[5]}

G = (V,E)

def topologicalSort1(G):
  A = []  
  indg = [0] * len(G)

# 진입차수 리스트 생성
  for i in range(len(G)):
    for j in range(len(G)):
      li = G[j]
      for k in range(len(li)):
        if li[k] = i:
          indg[i] += 1
   
  for i in range(len(indg)):
    if indg[i] == 0
      A.append(i)
  

        
    


SyntaxError: ignored

In [ ]:
# 교수님 풀이
V = {0:'냄비', 1:'라면봉지', 2:'점화', 3:'라면넣기', 4:'수프넣기', 5:'계란풀기'}
E = {0:[2], 1:[3,4], 2:[3,4,5], 3:[5], 4:[5]}
G = (V,E)

# 진입간선 구축
E2 = {}
for i in V.keys():
  E2[i] = set()
for i in E.keys():
  for j in E[i]:
    E2[j].add(i)
E2

{0: set(), 1: set(), 2: {0}, 3: {1, 2}, 4: {1, 2}, 5: {2, 3, 4}}

In [ ]:
import numpy as np

K = np.mat([[0]*7]*7) #행, 열
# k[A,B] -> a에서 B로 가는 진입간선
# 열에서 행으로..
# A=0, B=1, C=2, D=3, E=4, F=5, G=6
K[0,1] = 1
K[0,3] = 1
K[1,2] = 1
K[1,4] = 1
K[3,4] = 1
K[4,2] = 1
K[4,5] = 1
K[6,3] = 1

G = ['a','b','c','d','e','f','g']

print(K)

def topologicalSort(G):
    A = []
    while(True):
        for i in range(len(G)):
            sum=0
            for j in range(len(G)):
                sum += K[j,i]
            if sum ==0:
                A.append(G[i])
                for k in range(len(G)):
                    K[i,k] =0
                    K[k,i] =1
        if (len(A)==len(G)):
            break
    return A

print("위상 정렬 완료됨 : ",topologicalSort(G))


[[0 1 0 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]]
위상 정렬 완료됨 :  ['a', 'b', 'g', 'd', 'e', 'f', 'c']


In [ ]:
s